#!/bin/bash

#répertoire home
home="/home"
if [$# -eq 0 ]; then
echo "Usage: $0 <csv_file>"
exit 1
fi

csv_file = "$1"

cut -d ';' -f 1,6 "$csv_file" | sort | uniq -c | sort nr > "$temp/ctrajet.txt"

top_cond = $(head -n 10 "$temp/ctrajet.txt")

echo " top 10 conducteurs avec le plus de trajets différents:"
echo "$top_cond" | while read count name route_id; do 
printf "%-6s %-20s %-10s\n"
"$count" "$name" "$route_id" 
done
rm "$temp/ctrajet.txt"
exit 0
